name: Deploy Application

on: 
  push:
    branches:
      - main

jobs:
  create-deployment-artifacts:
    name: create deploy artifacts
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS
      - run: |
          npm install
          npm run prod